# Generated by Django 4.0.3 on 2022-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_core', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, choices=[('most watched', 'Most Watched'), ('top rated', 'Top Rated'), ('recently added', 'Recently Added')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='year_of_production',
            field=models.DateField(blank=True, null=True),
        ),
    ]
